### ISSUE TITLE
how to add datetime object into properties

### ISSUE THREAD

**Issue by priamai** [ArangoDB-Community/python-arango#175]
Hi there,
what is the best way to save a datetime property into a node or an edge?
Cheers.

**Comment by joowani** [comment]
Hi @priamai,

Sorry for the delay. Typically datetimes are stored as strings in [ISO format](https://en.wikipedia.org/wiki/ISO_8601) (e.g. `2021-10-10T19:36:59Z`) or as [unix timestamps](https://www.unixtimestamp.com/). There are plenty of libraries in Python (including the builtin in `datetime`) that support conversion from and to both forms.

If you are asking about native support for datetimes from the database itself, I would recommend asking the ArangoDB team directly.
