### ISSUE TITLE
Can't pickle <function ArangoClient.<lambda> at 0x7ff820d41840>: attribute lookup ArangoClient.<lambda> on arango.client failed

### ISSUE THREAD

**Issue by Gavingx** [ArangoDB-Community/python-arango#176]
hello, If I want to pickle a ArangoClient instance to a file? what should I do?

**Comment by joowani** [comment]
Hi @Gavingx,

Sorry for the delay. ArangoClient does not have keep track of any states that are worth pickling *except* for the [requests.Session objects](https://docs.python-requests.org/en/master/user/advanced/#session-objects). This [stackoverflow post](https://stackoverflow.com/questions/27526353/store-python-requests-session-in-persistent-storage) says that the `dill` library (vs. Python's builtin `pickle`) can serialize the session objects so I suggest you give that a try.
