### ISSUE TITLE
setuptools-scm[toml] dependency causing issue in Airflow ArangoDB Provider

### ISSUE THREAD

**Issue by pateash** [ArangoDB-Community/python-arango#194]
Hi, Team

We are trying to add ArangoDB provider to @apache/airflow.

The dependency

`
setuptools-scm[toml] (>=3.4)
`
automatically adds all files added to version control to the package that is built. This basically means that we have no way to control which of the source code files are used in which package.

The effect of this change was that when we build the **airflow package**, all providers are added to the package even if we did not include them which is caused our CI to fail.

Please find more information on PR https://github.com/apache/airflow/pull/22548

**Comment by potiuk** [comment]
Yeah. This is crazy stuff really.

**Comment by joowani** [comment]
@pateash @potiuk taking a look

**Comment by joowani** [comment]
`setuptools-scm[toml]` does seem pretty disruptive. I can remove it from the dependency. It's a shame since it was very useful for auto versioning.

**Comment by potiuk** [comment]
> `setuptools-scm[toml]` does seem pretty disruptive. I can remove it from the dependency. It's a shame since it was very useful for auto versioning.

You can add it as an extra

**Comment by aMahanna** [comment]
Hi @potiuk and @pateash 

I have opened a [PR](https://github.com/ArangoDB-Community/python-arango/pull/206) to re-introduce the auto versioning mechanic of `setuptools-scm`, but this time **without** specifying it as a `setup.py` dependency.

This should affect airflow's configuration of `python-arango`, but nevertheless I wanted to give you a heads up

**Comment by potiuk** [comment]
Thnks for letting us know. It's in build-system of pyproject.toml so I think it will be fine :)
