### ISSUE TITLE
How can I read the complete documents inside a collection?

### ISSUE THREAD

**Issue by rosenberg12** [ArangoDB-Community/python-arango#195]
Is there an option to read inside a `Collection` e.g. `students` the complete documents? 
My aim is that I can see the complete documents inside a dataframe, e.g. `import pandas as pd;
df=pd.json_normalize(result['...']['...'])`.

```py
from arango import ArangoClient

# Initialize the ArangoDB client.
client = ArangoClient()

# Connect to database as  user.
db = client.db(<db>, username=<username>, password=<password>)

print(db.collections())
students = db.collection('students')
#studens.getAllDocuments()
# for ...
#print(students)
```

**Comment by joowani** [comment]
Hi @rosenberg12,

You can use [students.all()](https://docs.python-arango.com/en/main/specs.html#arango.collection.Collection.all) or [students.export(...)](https://docs.python-arango.com/en/main/specs.html?highlight=export#arango.collection.Collection.export)

**Comment by rosenberg12** [comment]
@joowani thank you very much! That worked.
