### ISSUE TITLE
Breaking change in TLS Handling in 7.3.3

### ISSUE THREAD

**Issue by aquamatthias** [ArangoDB-Community/python-arango#201]
After upgrading python-arango from 7.3.1 to 7.3.3 we are no longer able to connect to arangodb servers with a TLS setup using a custom CA certificate.
The related change: #199 overrides the verify flag of the HTTP session with a boolean value and does not respect what has been defined before.

We followed the instructions on the docs page to set up our own HttpClient: https://docs.python-arango.com/en/main/http.html
and provide the CA bundle to the session via the verify property. See code [ArangoDBClient](https://github.com/someengineering/resoto/blob/main/resotocore/resotocore/db/arangodb_extensions.py#L13-L44)

In order to fix the behavior I would suggest one of the following:
- remove the `verify_certificate` argument, since the same goal can be accomplished using the HttpClient
- make the `verify_certificate` argument optional and default to `None`

I am happy to provide a fix if you agree with one of the suggestions.

**Comment by cw00dw0rd** [comment]
Thanks for bringing this up and I would vote for the second option as adding this option has been frequently requested. 
It would be great to add support for supplying a bundle or just supplying a boolean as you pointed out.

**Comment by lloesche** [comment]
requests.Session's `verify` is not a bool. It [can be either that or a string containing path to a CA_BUNDLE file or directory with certificates of trusted CAs](https://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification). Not super intuitive.

**Comment by cw00dw0rd** [comment]
I agree it isn't super intuitive from the link you provided and [here](https://github.com/psf/requests/blob/40956723f27daf5e0d9759208ca69cef236ab339/requests/sessions.py#L548) it seems to be either a boolean or path to cert bundle. 

I think defining it similar to @aquamatthias's supplied example `verify: Union[str, bool, None]` seems like a good approach. WDYT?

**Comment by cw00dw0rd** [comment]
Based on the above links `Requests` defaults `verify` to `True` and this seems like the more secure option as well. Should we instead allow for it to remain `True` but be optional? Open to it being `None` but that seems to go against the expectation of using the requests library, WDYT?

**Comment by aquamatthias** [comment]
The issue with the argument in that position: if defined it overrides everything that has been set at session level. That is why a default value (no matter which one) is not ideal. So I would propose the following:
```python
def __init__(...verify_override: Union[str, bool, None] = None):
   if verify_override is not None:
      for session in self._sessions:
         session.verify = verify_override
```

wdyt?

**Comment by cw00dw0rd** [comment]
That is a good point, your suggested solution works for me. Thanks again for pointing it out!

**Comment by aquamatthias** [comment]
Great. I will provide a PR.
