### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by mtgnoah** [ArangoDB-Community/python-arango#205]
NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb2fc2ea8b0>: Failed to establish a new connection: [Errno 111] Connection refused

This is the code to test. This is running on a community version. I used pip to install 
```
from arango import ArangoClient
client = ArangoClient(hosts='http://127.0.0.1:8529')
db = client.db(username="root", password="")
print(db.name)
result = db.create_database("test")
print(result)
```

**Comment by mtgnoah** [comment]
I am running this on windows 10 in a wsl2 container of ubuntu

**Comment by joowani** [comment]
Hi @mtgnoah, 

Looks like your code (which I'm assuming is running on Windows 10) is not able to reach the container. Are you sure the container has port 8529 published and is accessible from Windows 10? One thing you can do to check if the ArangoDB instance is reachable is to simply visit `http://127.0.0.1:8529` on your browser.

**Comment by mtgnoah** [comment]
@joowani I totally forgot I was running in wsl2. Look at this for help [wsl](https://superuser.com/questions/1679757/how-to-access-windows-localhost-from-wsl2) Once I ran it on regular windows it worked great
