### ISSUE TITLE
SSL ceritifcate supress verification 

### ISSUE THREAD

**Issue by raviapatel** [ArangoDB-Community/python-arango#225]
I get this error when trying to connect arango database instance.

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)'))'

From what i can understand this is because arango client is trying to verify SSL certificate. I can avoid this issue with PyArango by supressing verification of the certificate. I am trying to achieve same behaviour with python-arango. I see there is a "verify_certificate" option in client.db. Neverthless this doesn't work and when I look deeper into the code of python-arango I think it is not implemented is that the case?

**Comment by joowani** [comment]
Hi @raviapatel,

Are you using your own custom HTTP client ([doc](https://docs.python-arango.com/en/main/http.html))? Also in the later version of python-arango the option should be called [verify_override](https://github.com/ArangoDB-Community/python-arango/blob/main/arango/client.py#L49-L55).

**Comment by raviapatel** [comment]
...yes i am using http client i must check with verify_override.This version is not pushed on pypi i believe i will try to install it directly through repository

**Comment by raviapatel** [comment]
It works with this setting. But i must say that it is very counter intutive to set it to false to make it work

 ArangoClient(hosts="https://myhost/",      verify_override =False)
