### ISSUE TITLE
API Specification Docs not loading

### ISSUE THREAD

**Issue by cw00dw0rd** [ArangoDB-Community/python-arango#231]
API Spec information is no longer loading in the documentation: [https://docs.python-arango.com/en/main/specs.html](https://docs.python-arango.com/en/main/specs.html)

**Comment by joowani** [comment]
For now the dev one works: https://docs.python-arango.com/en/dev/

**Comment by tjoubert** [comment]
@joowani , do I understand correctly that `version.py` is generated by the tool `setuptools_scm`? If yes, is it possible to get this tool to write the version number in a text/config file somewhere that we can read from the code? This new file must become part of the deployed package when the driver is referenced/import by other projects.

**Comment by tjoubert** [comment]
@joowani , `setuptools_scm` says this about retrieving package version at runtime:
https://github.com/pypa/setuptools_scm#retrieving-package-version-at-runtime
Looks like we'll have to consider using `importlib.metadata`. What do you think?

**Comment by joowani** [comment]
The link you provided actually covers sphinx (our doc) also so I think we can just follow that: https://github.com/pypa/setuptools_scm#usage-from-sphinx

**Comment by tjoubert** [comment]
@joowani , so we have to do this:
```
from importlib_metadata import version, PackageNotFoundError

name = "python-arango"
driver_version = version(name)
```

Do you think it will work referencing the `python-arango` inside that package itself? The documentation seems to be referring to external packages that have been referenced/imported.

**Comment by joowani** [comment]
I'm not sure but you can test it out by running:

```
python -m sphinx -b html -W docs docs/_build
```
