### ISSUE TITLE
Documentation issue: ordered/geoJSON on collection.add_geo_index

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAzure** [ArangoDB-Community/python-arango#234]
In the base collection, it seems like the `ordered` index value is incorrectly documented. According to the[ArangoDB docs](https://www.arangodb.com/docs/stable/indexing-geo.html) this `geoJSON` being set to true turns on geoJSON support/indexing. Here in the docstring nothing of the sort is mentioned, and it implies that it has something to do with coordinate ordering.
https://github.com/ArangoDB-Community/python-arango/blob/86411ef40dc22b51a21eccdce8cc179b46d322f1/arango/collection.py#L1169-L1200

It took me way too long to figure out how to turn on geoJSON support because of this.

**Comment by joowani** [comment]
Thank you for the report @Adrian-at-CrimsonAuzre. Will take a look when my time allows.
