### ISSUE TITLE
Authenticate using User JWT-Token

### ISSUE THREAD

**Issue by geenen124** [ArangoDB-Community/python-arango#238]
It would be great to support User JWT Token-based authentication for a database connection. The benefit is that the python-arango client would not need to know any username/password credentials, and a user does not need the superuser access that the current `superuser_token` argument supports. This does come with added responsibility for a user authenticating this way since there is no guarantee that the token is still valid.

For example, loading a JWT from environment variables:
```python
from arango import ArangoClient
import os

# Initialize the ArangoDB client.
client = ArangoClient()

# get user JWT
token = os.environ["ARANGODB_USER_JWT"]

# Connect to "test" database as a user using the token.
db = client.db('test', user_token=token)
```

**Comment by CryptoNinjaGeek** [comment]
Hi @geenen124 

The request has been added to our backlog and will be prioritized for a future release.
