### ISSUE TITLE
merge functionality

### ISSUE THREAD

**Issue by ositaunus** [ArangoDB-Community/python-arango#248]
is there a  `db.merge_link/node` functionality that would check if the node or link attributes were the same for an already existing node or link before inserting. this is very useful to avoid polluting a graph with duplicates

**Comment by apetenchea** [comment]
Hello @ositaunus,

Currently, our driver does not have a `merge_link` or `merge_node` functionality that performs checks for duplicate node or link attributes before inserting. The purpose of our driver is to serve as an interface for the database. While we aim to make it as user-friendly as possible, adding such functionality is presently outside our scope.

The `link` function is essentially shorthand for inserting a new edge into an edge collection. However, you can implement the checks yourself before calling it by using `has_edge` and `has_vertex` functions to determine if a node or link already exists.

While we understand the usefulness of a merge functionality to prevent duplicate entries, the flexibility of our current design allows users to define their own requirements for what constitutes a duplicate. Nevertheless, we appreciate your feedback and will consider it for future updates.

Please checkout our [Graphs examples](https://docs.python-arango.com/en/main/graph.html) for more information.
