### ISSUE TITLE
Unable to disable request timeout

### ISSUE THREAD

**Issue by 153957** [ArangoDB-Community/python-arango#261]
Previously it was possible to disable the timeout for the HTTP client by setting `request_timeout` to `None`, but after: https://github.com/ArangoDB-Community/python-arango/pull/257 it 'has' to be an int of float.
So the timeout can no longer be easily disabled (can of course be set super high, but that means having to set it to *something* instead of clearly nothing/unlimited).

Please allow `None` as a value for the `request_timeout`.

**Comment by aMahanna** [comment]
Hey @153957, #265 should fix the `mypy` issue you are seeing
