### ISSUE TITLE
bind_vars type hints are incomplete

### ISSUE THREAD

**Issue by valentingregoire** [ArangoDB-Community/python-arango#288]
According to [this](https://github.com/ArangoDB-Community/python-arango/blob/main/arango/aql.py#L176) and [this](https://github.com/ArangoDB-Community/python-arango/blob/main/arango/aql.py#L260) piece of code, the bind vars values should be strings. That seems to be incorrect, since values in ArangoDB are not always strings.

Docs: https://docs.arangodb.com/3.11/aql/fundamentals/data-types/

**Comment by apetenchea** [comment]
Hi @valentingregoire,

You're right, thanks for pointing out this discrepancy in the type hinting.

Given your understanding of the issue, we always encourage contributions and would be happy to offer you the opportunity to address this if you're interested. For smaller pull requests, we aim to make this experience collaborative. However, if you'd prefer not to or if you're pressed for time, I'm happy to take a look and address it when I get a chance.

Please let me know how you'd like to proceed!

**Comment by valentingregoire** [comment]
I will take care of it, no worries.

**Comment by valentingregoire** [comment]
@apetenchea, PR is submitted: https://github.com/ArangoDB-Community/python-arango/pull/289

Feel free to change stuff, provide feedback, ...

**Comment by apetenchea** [comment]
> @apetenchea, PR is submitted: #289
> 
> Feel free to change stuff, provide feedback, ...

Great, thanks!
